name: update-sources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run update
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Commit changes
        run: |
          git config --global user.name 'Daniel Bonofiglio'
          git config --global user.email 'dev@dan.uy'
          git add .
          git commit -m "update sources $(date -I)"
          git push
