name: update-sources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run update
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: "Update sources"
          add: 'sources.json'
